---
version: '2'
services:
  wlpib:
    image: wplib/wplib:v0.1
    ports:
      - 80:80
      - 443:443
      - 3306:3306
      - 6379:6379
      - 9000:9000
    volumes:
      - ./www:/usr/share/nginx/html